# Generated by Django 4.2.7 on 2025-11-21 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('job_location', models.CharField(max_length=255)),
                ('job_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('job_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('expected_duration', models.IntegerField(help_text='Expected duration in minutes')),
                ('scheduled_start', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='trips.driver')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('start_odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_fuel_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_fuel_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('route_compliance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_after_hours', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.driver')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.job')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bakkie', 'Bakkie'), ('van', 'Van'), ('truck', 'Truck'), ('sedan', 'Sedan')], max_length=20)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival at Job Site'), ('delay', 'Delay'), ('fuel_stop', 'Fuel Stop'), ('incident', 'Incident'), ('photo', 'Photo'), ('completed', 'Job Completed'), ('other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trip_events/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.vehicle'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='trips.vehicle'),
        ),
        migrations.CreateModel(
            name='GPSRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
